version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: piaz
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
